### PR TITLE
Experimental

### PR DESCRIPTION
**Pull request by shiroge**

### CODE REVIEW

**Comment by peterbrinck** [comment]
I like that you've split the big `main.js` into smaller js files, it's easier to get around

**Comment by shiroge** [comment]
The code was pretty much rewritten too, it's now much easier to make additions.

I still want to find a way to merge them back for release, though. It's faster to load without having to fetch so many .js files.

**Comment by peterbrinck** [comment]
You could use something like Grunt to minify all the files together
Have a `src` folder, with all the JS files split, and then have a grunt task running to take all the JS files and minify them into a single `main.min.js` file inside `assets/`

**Comment by shiroge** [comment]
I'm still pretty new to JS, I'll have to take a look on how to do that. Thanks for the tip though. :)

**Comment by peterbrinck** [comment]
I can make the Grunt task if you don't feel like doing it

**Comment by shiroge** [comment]
No need to, it will be a good learning experience. I'll ask for help if I get too stuck.

**Comment by peterbrinck** [comment]
Okay, cool :smile:

**Comment by shiroge** [comment]
On a second though, you can do it if you want. I want to focus on new features.

**Comment by peterbrinck** [comment]
Sure
I'll look into it tomorrow (it's close to midnight here)

**Comment by shiroge** [comment]
Don't worry, take your time. This update might take a while, I wanna do a lot of new stuff.

**Pull request merged**
